export const listDestinationRecommendationObjectRequest = {
    description: 'Lists destination recommendations for user.',
    tags: ['Destination Recommendation'],
    security: [{ bearerAuth: [] }],
    params: {
        type: 'object',
        properties: {
            userId: {
                type: 'string',
                description: 'The mongo id for the user.'
            }
        },
        required: [
            "userId"
        ]
    },
    response: {
        200: {
            description: 'Successful response',
            type: 'array',
            example: [
                {
                    "_id": "6609ce2b4bf25c7314563b37",
                    "city": "Missoula",
                    "state": "MT",
                    "hasZoo": false,
                    "hasSkiing": true,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 5
                },
                {
                    "_id": "6609ce0f4bf25c7314563ad5",
                    "city": "Des Moines",
                    "state": "IA",
                    "hasZoo": true,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 4
                },
                {
                    "_id": "6609cfce4bf25c7314563cd3",
                    "city": "Topeka",
                    "state": "KS",
                    "hasZoo": true,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 3
                },
                {
                    "_id": "6609cfe94bf25c7314563d43",
                    "city": "Columbia",
                    "state": "MO",
                    "hasZoo": true,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 2.5
                },
                {
                    "_id": "6609cfed4bf25c7314563d58",
                    "city": "Grand Island",
                    "state": "NE",
                    "hasZoo": true,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 3.5
                },
                {
                    "_id": "6609ce634bf25c7314563c00",
                    "city": "Parkersburg",
                    "state": "WV",
                    "hasZoo": false,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": false,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 2.5
                },
                {
                    "_id": "6609cfd44bf25c7314563ceb",
                    "city": "Lake Charles",
                    "state": "LA",
                    "hasZoo": false,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": false,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 2.5
                },
                {
                    "_id": "6609d0154bf25c7314563e00",
                    "city": "Brookings",
                    "state": "SD",
                    "hasZoo": false,
                    "hasSkiing": false,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": false,
                    "hasAquarium": false,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 2.5
                },
                {
                    "_id": "6609ce084bf25c7314563aba",
                    "city": "Boise",
                    "state": "ID",
                    "hasZoo": true,
                    "hasSkiing": true,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": true,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 2.5
                },
                {
                    "_id": "6609ce184bf25c7314563af5",
                    "city": "Portland",
                    "state": "ME",
                    "hasZoo": true,
                    "hasSkiing": true,
                    "hasCasino": true,
                    "hasSportStadium": true,
                    "hasMuseum": true,
                    "hasNightLife": true,
                    "hasAquarium": true,
                    "hasBeach": true,
                    "hasMountains": true,
                    "hasOutdoorActivities": true,
                    "hasArtisticsPlays": true,
                    "hasAmusementPark": false,
                    "estimatedRating": 2.5
                }
            ]
        },
    },
}